"use strict";

function minerStatus(id){
  const h=HARDWARE.find(x=>x.id===id),count=state.hardware?.[id]||0;if(!h||count<1)return{kind:"idle",label:"Not installed"};
  const reason=hardwareOfflineReason(h),hardwareFault=maintenanceCondition(h)<65||!!activeServiceJob(id);
  if(hardwareFault)return{kind:"hardware",label:reason||"Hardware fault"};
  if(reason)return{kind:"config",label:reason};
  if(!state.power||state.debt>0||state.policyLock||siteOutage()||!fleet().within)return{kind:"power",label:state.debt>0?"Grid disconnected":state.policyLock||siteOutage()?"Site unavailable":"No electrical power"};
  return{kind:"online",label:"Online and hashing"};
}
function minerStatusSvg(id){const status=minerStatus(id);if(status.kind==="online")return `<circle class="miner-online" cx="56" cy="8" r="2"><title>${status.label}</title></circle>`;if(status.kind==="power")return `<g><title>${status.label}</title><path class="miner-power-warning" d="M56 1 63 14H49z"/><path d="m57 4-4 5h3l-2 4 6-6h-3l2-3z" fill="#17130b"/></g>`;if(status.kind==="hardware")return `<g><title>${status.label}</title><path class="miner-hardware-fire" d="M56 15c-5 0-8-3-7-7 1-3 4-4 5-7 3 2 4 4 3 6 2-1 3-2 3-4 4 4 5 7 3 10-1 2-4 2-7 2z"/><path d="M56 13c-2 0-3-1-2-3 0-1 1-2 2-3 2 2 3 4 0 6z" fill="#ffd36c"/></g>`;if(status.kind==="config")return `<g><title>${status.label}</title><path class="miner-config-warning" d="M56 1 63 14H49z"/><path d="M56 5v5m0 2v1" stroke="#17130b" stroke-width="1.5"/></g>`;return `<circle class="ops-pulse" cx="56" cy="8" r="2"><title>${status.label}</title></circle>`}
function minerSvg(id){
  const art=id==="laptop"?`<path d="M13 11h38v23H13z" fill="#172224" stroke="#71837d"/><path d="M8 35h48l4 5H4z" fill="#253235"/><rect x="18" y="15" width="28" height="15" fill="#0c1516"/><path d="M24 39h16" stroke="#86c79a"/>`:id==="cpu"?`<rect x="4" y="9" width="32" height="23" rx="1" fill="#172224" stroke="#71837d"/><rect x="8" y="13" width="24" height="15" fill="#0c1516"/><path d="M20 32v5m-8 2h16" stroke="#86c79a" stroke-width="2"/><rect x="42" y="5" width="17" height="36" rx="2" fill="#202d2f" stroke="#81938e"/><path d="M46 12h9M46 17h9M46 22h9" stroke="#526560"/><circle cx="51" cy="34" r="2" fill="#86c79a"/>`:(id==="5870"||id==="gpurig")?`<rect x="7" y="12" width="49" height="25" rx="2" fill="#172224" stroke="#71837d"/><circle cx="22" cy="24" r="8" fill="#0b1011" stroke="#86c79a"/><circle cx="42" cy="24" r="8" fill="#0b1011" stroke="#86c79a"/><path d="M57 18v13M10 39h40" stroke="#ffc267"/>`:id==="fpga"?`<path d="M11 9h42v30H11z" fill="#1b292b" stroke="#71837d"/><rect x="17" y="15" width="12" height="12" fill="#f0a92f"/><rect x="35" y="15" width="12" height="12" fill="#f0a92f"/><path d="M15 33h34M9 15h4M9 22h4M9 29h4" stroke="#86c79a"/>`:id==="avalon"?`<rect x="6" y="10" width="52" height="28" rx="3" fill="#223033" stroke="#8ba09a"/><circle cx="18" cy="24" r="9" fill="#0b1011" stroke="#ffc267"/><circle cx="36" cy="24" r="9" fill="#0b1011" stroke="#ffc267"/><path d="M51 16v16M54 16v16" stroke="#86c79a"/>`:id==="s19hydro"?`<rect x="7" y="11" width="50" height="25" rx="5" fill="#16343a" stroke="#71c9d7" stroke-width="2"/><path d="M13 17h26M13 23h26M13 29h26" stroke="#9be5eb"/><circle cx="47" cy="19" r="5" fill="none" stroke="#3fa9b9" stroke-width="2"/><circle cx="47" cy="29" r="5" fill="none" stroke="#3fa9b9" stroke-width="2"/><path d="M9 40h46" stroke="#3fa9b9" stroke-width="3"/>`:id==="s21hydro"?`<path d="M5 13h54v23H5z" fill="#17313a" stroke="#71c9d7" stroke-width="2"/><path d="M11 19h28M11 25h28M11 31h28" stroke="#5dd2df"/><path d="M44 16c11 2 11 15 0 17M48 16c11 2 11 15 0 17" fill="none" stroke="#71c9d7" stroke-width="2"/><path d="M8 39c9 5 16-5 25 0s16-5 25 0" fill="none" stroke="#3fa9b9" stroke-width="2"/>`:`<path d="M5 11h54v27H5z" fill="#172224" stroke="#81938e"/><circle cx="18" cy="24.5" r="10" fill="#0b1011" stroke="#86c79a"/><path d="M18 15v19M9 24.5h18M11 18l14 13M25 18 11 31" stroke="#86c79a" stroke-width="1"/><rect x="35" y="17" width="16" height="4" fill="#f0a92f"/><rect x="35" y="25" width="16" height="4" fill="#526560"/><path d="M6 40h52" stroke="#ffc267"/>`;
  return `<svg class="miner-icon" viewBox="0 0 64 46" aria-label="${id} mining hardware illustration">${art}${minerStatusSvg(id)}</svg>`
}
function tabCommandVisual(kind){
  const fs=fleet(),learning=learningItem();let title,copy,stats,art;
  if(kind==="mine"){const owned=HARDWARE.filter(h=>(state.hardware[h.id]||0)>0),shown=owned.slice(-8);title="Fleet command";copy=narrativeCopy("mine");stats=`<span><b>${fs.count}</b> machines</span><span><b>${fmtHash(fs.hash)}</b> active hash</span><span><b>${fs.kw.toFixed(1)} kW</b> draw</span>`;art=`<div class="fleet-actual" aria-label="Actual owned mining hardware">${shown.map(h=>`<div class="fleet-actual-unit">${minerSvg(h.id)}<b>×${state.hardware[h.id]}</b><span class="fleet-actual-label">${h.name}</span></div>`).join("")}${owned.length>shown.length?`<div class="fleet-extra">+${owned.length-shown.length}<br>types</div>`:""}</div>`}
  else if(kind==="market"){title="Market terminal";copy=narrativeCopy("market");stats=`<span><b>${fmtUsd(state.cash)}</b> liquid fiat</span><span><b>${fmtBtc(totalBtc())}</b> BTC exposure</span><span><b>${fmtUsd(equityValue())}</b> equities</span><span><b>${state.time<MARKET?"—":fmtUsd(priceAt(state.time))}</b> BTC / USD</span>`;art=`<svg class="tab-art" viewBox="0 0 360 165" aria-label="Market price and settlement flow"><path d="M22 128H338M22 93H338M22 58H338" stroke="#283334"/><path d="M23 120 C65 105 77 128 112 92 S170 104 201 55 S260 94 285 43 S319 66 338 25" fill="none" stroke="#f0a92f" stroke-width="4"/><circle class="glow" cx="338" cy="25" r="5"/><path d="M50 143h70M240 143h70" stroke="#86c79a" stroke-width="5"/><path d="M119 143h122" stroke="#82948f" stroke-width="2" stroke-dasharray="5 5"/><text x="45" y="158" fill="#a8b4b0" font-size="11">FIAT</text><text x="261" y="158" fill="#a8b4b0" font-size="11">BTC</text></svg>`}
  else if(kind==="custody"){title="Custody map";copy=narrativeCopy("custody");stats=`<span><b>${fmtBtc(controlled())}</b> keys controlled</span><span><b>${fmtBtc(claims())}</b> venue claims</span><span><b>${nodeOnline()?"online":"offline"}</b> node</span>`;art=`<svg class="tab-art" viewBox="0 0 360 165" aria-label="Bitcoin custody vault"><path d="M82 23h122l45 37v70l-106 24-106-24V60z" fill="#152426" stroke="#86c79a" stroke-width="3"/><circle cx="143" cy="87" r="30" fill="#0b1011" stroke="#f0a92f" stroke-width="3"/><path d="M143 68v38M130 80h25M130 95h25" stroke="#f0a92f" stroke-width="3"/><path d="M255 51h45v57h-45z" fill="#1c292b" stroke="#81938e"/><path d="M264 67h27M264 79h27M264 91h27" stroke="#86c79a"/><circle class="glow" cx="278" cy="60" r="3"/></svg>`}
  else if(kind==="learn"){title="Knowledge desk";copy=narrativeCopy("learn");stats=`<span><b>${state.knowledge.toFixed(1)}</b> knowledge</span><span><b>${state.points}</b> tech points</span><span><b>${learning?"occupied":"available"}</b> learning slot</span>`;art=`<svg class="tab-art" viewBox="0 0 360 165" aria-label="Books and podcast learning"><path d="M35 38c42-15 74-6 102 15v78c-29-21-61-29-102-14zM137 53c29-21 61-30 102-15v79c-41-15-73-7-102 14z" fill="#1c2b2d" stroke="#86c79a" stroke-width="3"/><path d="M55 66h58M55 82h48M55 98h54M160 66h58M160 82h48M160 98h54" stroke="#82948f"/><path d="M272 57c28 12 28 39 0 51M288 45c43 22 43 53 0 75" fill="none" stroke="#f0a92f" stroke-width="5"/><circle class="glow" cx="257" cy="82" r="9"/></svg>`}
  else{title="Technology tree";copy=narrativeCopy("tech");stats=`<span><b>${state.points}</b> unspent points</span><span><b>${state.skills.length}</b> upgrades</span><span><b>${SKILLS.length}</b> available paths</span>`;art=`<svg class="tab-art" viewBox="0 0 360 165" aria-label="Technology skill network"><path d="M72 82h72M144 82l65-42M144 82l65 42M209 40h74M209 124h74" stroke="#526560" stroke-width="3"/><circle cx="55" cy="82" r="18" fill="#172628" stroke="#f0a92f" stroke-width="4"/><circle cx="144" cy="82" r="17" fill="#172628" stroke="#86c79a" stroke-width="4"/><circle cx="226" cy="40" r="17" fill="#172628" stroke="#86c79a" stroke-width="4"/><circle cx="226" cy="124" r="17" fill="#172628" stroke="#86c79a" stroke-width="4"/><circle class="glow" cx="301" cy="40" r="10"/><circle cx="301" cy="124" r="10" fill="#f0a92f"/></svg>`}
  return `<section class="card span-12 tab-command-${kind}"><div class="tab-command"><div class="tab-command-copy"><div class="hero-kicker">${narrativeEra().label}</div><h2>${title}</h2><p>${copy}</p><div class="tab-command-stats">${stats}</div></div><div class="tab-command-art">${art}</div></div></section>`;
}
function narrativeBanner(kind,title){return `<section class="card span-12 narrative-${kind}"><div class="card-pad"><div class="hero-kicker">${narrativeEra().label}</div><h2 style="margin:8px 0">${title}</h2><p style="color:var(--muted);line-height:1.65;max-width:900px;margin:0">${narrativeCopy(kind)}</p></div></section>`}
function enhanceMine(){
  const grid=document.querySelector(".content .grid");if(!grid)return;
  grid.insertAdjacentHTML("afterbegin",tabCommandVisual("mine"));
  const fs=fleet(),reserved=plannedFleetProjection(),ordered=state.procurementOrders.reduce((sum,o)=>sum+Number(o.qty||0),0),staged=Object.values(state.inactiveHardware||{}).reduce((sum,n)=>sum+Number(n||0),0),banner=`<div class="shopping-banner span-12"><b>Live mine desk — ${state.speed>0?`timeline running at ${state.speed}×`:"timeline manually paused"}</b><span>Buy, sell and activate miners without leaving this screen. Prices and available quantities update as the simulation advances.</span></div>`;
  grid.insertAdjacentHTML("afterbegin",`${banner}<section class="card span-12"><div class="metric-row"><div class="metric"><div class="label">Machines</div><strong>${fs.count}</strong><small>${ordered||staged?`${ordered?`${ordered} ordered`:""}${ordered&&staged?" · ":""}${staged?`${staged} awaiting activation`:""}`:"Active units deployed"}</small></div><div class="metric"><div class="label">Machine capacity</div><strong>${reserved.space} / ${facility().space}</strong><small>${ordered?`${fs.space} deployed · ${reserved.space-fs.space} reserved`:"Floor units used / available"}</small></div><div class="metric"><div class="label">Electrical capacity</div><strong>${reserved.kw.toFixed(2)} / ${reserved.cap.toFixed(1)} kW</strong><small>${ordered?`${fs.kw.toFixed(2)} deployed · ${(reserved.kw-fs.kw).toFixed(2)} reserved`:`${Math.max(0,reserved.cap-reserved.kw).toFixed(2)} kW remaining`}</small></div><div class="metric"><div class="label">Current facility</div><strong>${facility().name}</strong><small>Upgrade in Facilities</small></div></div></section>`);
  if(state.procurementOrders.length)grid.insertAdjacentHTML("afterbegin",`<section class="card span-12"><div class="card-head"><h2>Outstanding miner deliveries</h2><div class="meta">PAID · NOT YET HASHING</div></div><div class="card-pad venue-grid">${state.procurementOrders.map(o=>{const h=HARDWARE.find(x=>x.id===o.id),days=Math.max(0,Math.ceil((o.due-state.time)/DAY));return `<article class="venue"><div class="risk ${o.slipped?"high":"medium"}">${o.slipped?"DELIVERY SLIPPED":o.label}</div><h3>${o.qty} × ${h?.name||o.id}</h3><p>ETA ${dateFmt(o.due)} · ${days} simulation days remaining.</p><div class="trade-sub">${Math.round((o.risk||0)*100)}% original slippage risk · delivery moves the batch into staged inventory.</div></article>`}).join("")}</div></section>`);
  const arrivals=HARDWARE.filter(h=>(state.inactiveHardware?.[h.id]||0)>0);if(arrivals.length)grid.insertAdjacentHTML("afterbegin",`<section class="card span-12"><div class="card-head"><h2>Delivered miners awaiting activation</h2><div class="meta">ARRIVED · PAID · NOT HASHING</div></div><div class="card-pad venue-grid">${arrivals.map(h=>{const qty=state.inactiveHardware[h.id];return `<article class="venue active">${minerSvg(h.id)}<div class="risk medium">DEPLOYMENT REQUIRED</div><h3>${qty} × ${h.name}</h3><p>The shipment is staged at ${facility().name}. Activate it to connect power, networking and pool credentials.</p><div class="trade-sub">Reserves ${fmtNum(h.w*qty/1000)} kW and ${fmtNum(h.space*qty)} floor units once active.</div><button class="action small primary" data-action="activate-hw" data-id="${h.id}">Activate ${qty} miner${qty===1?"":"s"}</button></article>`}).join("")}</div></section>`);
  const mineVisual=grid.querySelector(".tab-command-mine");if(mineVisual)grid.prepend(mineVisual);
  document.querySelectorAll(".catalog .item").forEach(card=>{const h=HARDWARE.find(x=>x.id===card.dataset.hwId);if(!h)return;const reason=hardwareOfflineReason(h);card.insertAdjacentHTML("afterbegin",minerSvg(h.id));if(reason)card.insertAdjacentHTML("beforeend",`<div class="trade-sub" style="color:var(--red)">Will remain offline: ${reason}</div>`);if(h.permanent||state.time<MARKET)return;const unitBtc=hardwareUnitCost(h)/priceAt(state.time),reserved=plannedFleetProjection(),capacityMax=Math.max(0,Math.min(Math.floor(Math.max(0,reserved.cap*1000-reserved.w)/Math.max(1,h.w)),Math.floor(Math.max(0,facility().space-reserved.space)/Math.max(1,h.space)))),max=Math.max(0,Math.min(Math.floor(state.wallets.hot/unitBtc),capacityMax)),foot=card.querySelector(".item-foot");if(foot)foot.insertAdjacentHTML("beforeend",`<div class="actions"><button class="action small" data-action="buy-hw-btc" data-id="${h.id}" data-value="1" ${max<1?"disabled":""}>Buy 1 · ${fmtCompactBtc(unitBtc)}</button><button class="action small" data-action="buy-hw-btc" data-id="${h.id}" data-value="${max}" ${max<1?"disabled":""}>Buy max · ${fmtCompactBtc(unitBtc*max)} (${fmtCompactNumber(max)} miners)</button></div>`);});
}
function enhanceMarket(){
  const grid=document.querySelector(".content .grid");if(!grid)return;
  const headlineMetrics=grid.querySelector(".metric-row");if(headlineMetrics&&headlineMetrics.children[2])headlineMetrics.children[2].innerHTML=`<div class="label">Equities</div><strong>${fmtUsd(equityValue())}</strong><small>Strategy shares · not liquid fiat</small>`;
  setTimeout(()=>{if(!grid.querySelector(".tab-command-market"))grid.insertAdjacentHTML("afterbegin",tabCommandVisual("market"))},0);
  const venueGrid=grid.querySelector(".venue-grid");if(venueGrid)venueGrid.insertAdjacentHTML("afterbegin",`${venueCard("bitfinex","Bitfinex","high","Deep liquidity and professional tooling, with historic security and custody risk.")}${venueCard("quadriga","QuadrigaCX","extreme","Convenient Canadian access with severe counterparty and custody risk.")}`);
  const lightningNote=[...grid.querySelectorAll(".modal-note")].find(el=>el.textContent.startsWith("Requires a full node."));if(lightningNote)lightningNote.textContent="Requires a synchronized dedicated primary node in archival or relay mode. A remote verification backup deliberately does not hold the Lightning service or channel keys.";
  const securities=STRATEGY_SECURITIES.filter(s=>state.time>=at(s.date));if(securities.length)grid.insertAdjacentHTML("beforeend",`<section class="card span-12"><div class="card-head"><h2>Strategy capital structure</h2><div class="meta">MODELLED PRICE EXPOSURE · FIAT PAYOUTS WHERE APPLICABLE</div></div><div class="card-pad"><p style="color:var(--muted);line-height:1.6;margin-top:0">These instruments are modelled from Strategy's Bitcoin-treasury logic. MSTR is amplified equity exposure; the preferred series target different cash-income profiles. Prices are game models linked to Bitcoin's historical path, not historical security prices.</p><div class="venue-grid">${securities.map(s=>{const shares=state.strategy[s.id]||0,value=strategyValue(s.id),income=shares*strategyPrice(s.id)*s.yield/365*30.4375;return `<article class="venue ${shares>0?"active":""}"><div class="risk ${s.yield?"medium":"high"}">${s.ticker} · ${s.yield?`${(s.yield*100).toFixed(0)}% modelled annual fiat yield`:"leveraged BTC equity exposure"}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="trade-value">${fmtUsd(value)}</div><div class="trade-sub">${shares.toFixed(2)} shares · ${fmtUsd(strategyPrice(s.id))}/share${s.yield?` · ~${fmtUsd(income)}/mo`:""}</div><div class="actions"><button class="action small primary" data-action="buy-strategy" data-id="${s.id}" data-value=".1" ${state.cash<1?"disabled":""}>Buy 10% cash</button><button class="action small" data-action="buy-strategy" data-id="${s.id}" data-value=".25" ${state.cash<1?"disabled":""}>Buy 25%</button><button class="action small" data-action="sell-strategy" data-id="${s.id}" data-value=".25" ${shares<=0?"disabled":""}>Sell 25%</button></div></article>`}).join("")}</div><p class="modal-note" style="margin-top:10px">STRC income is paid into fiat daily in-game. Other preferred dividends are also simplified as daily fiat accruals; no dividend is guaranteed in reality.</p></div></section>`);
  const available=SPECULATIONS.filter(s=>state.time>=at(s.date)&&!state.speculations.includes(s.id)).sort((a,b)=>at(b.date)-at(a.date));
  if(!available.length)return;
  grid.insertAdjacentHTML("beforeend",`<section class="card span-12"><div class="card-head"><h2>Speculative side bets</h2><div class="meta">MODELLED · HIGH RISK · ONE ATTEMPT EACH</div></div><div class="card-pad"><p style="color:var(--muted);line-height:1.6;margin-top:0">These are optional historical-era opportunities, not investment advice. Each risks BTC from your hot wallet; outcomes are deterministic within this run and losses are more likely than gains.</p><div class="venue-grid">${available.map(s=>`<article class="venue"><div class="risk high">${Math.round(s.chance*100)}% modelled chance · ${s.payout.toFixed(1)}× return if it hits</div><h3>${s.name}</h3><p>${s.desc}</p><div class="trade-sub">${s.kind} · launched ${dateFmt(at(s.date),true)}</div><div class="actions"><button class="action small primary" data-action="speculate" data-id="${s.id}" data-value=".1" ${state.wallets.hot<=0?"disabled":""}>Risk 10% hot BTC</button><button class="action small" data-action="speculate" data-id="${s.id}" data-value=".25" ${state.wallets.hot<=0?"disabled":""}>Risk 25%</button></div></article>`).join("")}</div></div></section>`);
}
