"use strict";

function settlementForecastVisual(){
  const x=settlementForecast(),stateClass=x.cashAfter<0?"short":x.cashAfter<x.estimated*.2?"tight":"",status=x.cashAfter<0?`SHORT ${fmtUsd(Math.abs(x.cashAfter))} · fleet will disconnect if you do not raise cash or shut down`:x.cashAfter<x.estimated*.2?`TIGHT · only ${fmtUsd(x.cashAfter)} remains after settlement`:`COVERED · ${fmtUsd(x.cashAfter)} projected cash after settlement`;
  const labels={energy:"Electricity",rent:"Facility rent",internet:"Internet",staff:"Payroll",insurance:"Insurance",nodeNetwork:"Node services",finance:"Finance interest",other:"Prior accrued costs"},lines=Object.entries(x.breakdown).filter(([key,value])=>value>0||["energy","rent","internet"].includes(key)),recurring=monthlyCost().total+(state.projectLoan*(hasStaff("treasurer")?.009:.012)),stops=[{date:x.dueAt,amount:x.estimated,note:`${x.days} day${x.days===1?"":"s"} remaining · current accrued costs included`},{date:nextSettlementDate(1),amount:recurring,note:"One full month at current contracts, staffing and fleet"},{date:nextSettlementDate(2),amount:recurring,note:"Planning estimate · changes when the operation changes"}];
  return `<section id="settlement-forecast" class="card span-12"><div id="settlement-forecast-panel" class="settlement-forecast ${stateClass}"><h3 id="forecast-heading">Forthcoming obligations · next settlement ${dateFmt(x.dueAt)}</h3><div class="obligation-timeline">${stops.map((stop,index)=>`<div class="obligation-stop"><time>${index===0?"Next settlement":"Forecast"} · ${dateFmt(stop.date)}</time><b ${index===0?'id="forecast-next-total"':""}>${fmtUsd(stop.amount)}</b><small ${index===0?'id="forecast-next-note"':""}>${stop.note}</small></div>`).join("")}</div><div class="forecast-grid"><div><small>Accrued so far</small><b id="forecast-accrued">${fmtUsd(state.bill)}</b></div><div><small>Still to accrue</small><b id="forecast-remaining">${fmtUsd(x.remaining)}</b></div><div><small>Projected bill</small><b id="forecast-total">${fmtUsd(x.estimated)}</b></div><div><small>Cash afterwards</small><b id="forecast-cash-after">${fmtUsd(x.cashAfter)}</b></div></div><div class="bill-breakdown">${lines.map(([key,value])=>`<div class="bill-line"><span>${labels[key]||key}</span><b id="forecast-line-${key}">${fmtUsd(value)}</b></div>`).join("")}</div><div id="forecast-bar" class="forecast-bar" style="--forecast:${x.coverage}%"><i></i></div><div id="forecast-status" class="forecast-status">${status}</div><p class="modal-note" style="margin:10px 0 0">Forecasts use current fleet power, facility, jurisdiction, internet plan, payroll, node services, insurance and project-finance terms. Hardware orders are prepaid and therefore shown with delivery dates in Mine rather than as future bills.</p></div></section>`;
}
function connectivityPlansVisual(){
  const r=region(),monitoring=hasSkill("monitoring")?.75:1;
  return `<section class="card span-12"><div class="card-head"><h2>Internet & propagation</h2><div class="meta">${r.name.toUpperCase()} · MODELLED JURISDICTION PRICING</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">Current plan</div><strong>${connectivityPlan().name}</strong><small>${fmtUsd(internetMonthlyCost())}/month at ${facility().name}</small></div><div class="metric"><div class="label">Monthly incident chance</div><strong>${fmtPct(connectivityIncidentRisk()*100)}</strong><small>Before deterministic incident roll</small></div><div class="metric"><div class="label">Mining propagation</div><strong>${connectivityMiningFactor()>=1?"+":""}${((connectivityMiningFactor()-1)*100).toFixed(1)}%</strong><small>Applied to effective expected revenue</small></div><div class="metric"><div class="label">Jurisdiction base</div><strong>${fmtUsd(r.internet||75)}/mo</strong><small>Scaled by facility size and service tier</small></div></div><div class="venue-grid" style="margin-top:12px">${CONNECTIVITY_PLANS.map(plan=>{const selected=plan.id===state.connectivity,available=!plan.minFacility||facilityTier()>=plan.minFacility,cost=(r.internet||75)*plan.mult*connectivityScale(),risk=(r.netRisk||.02)*plan.risk*monitoring,prop=(plan.payout-1)*100;return `<article class="venue ${selected?"active":""} ${available?"":"locked"}"><div class="risk ${selected?"low":plan.risk<.5?"low":"medium"}">${selected?"CURRENT PLAN":available?`${fmtPct(risk*100)} MONTHLY INCIDENT CHANCE`:`TIER ${plan.minFacility} FACILITY REQUIRED`}</div><h3>${plan.name}</h3><p>${plan.desc}</p><div class="trade-value">${fmtUsd(cost)}/mo</div><div class="plan-stats"><span>${prop>=0?"+":""}${prop.toFixed(1)}% propagation</span><span>${Math.round((1-plan.risk)*100)}% outage-risk reduction</span></div><button class="action small ${selected?"":"primary"}" data-action="connectivity" data-id="${plan.id}" ${selected||!available?"disabled":""}>${selected?"Selected":available?"Use this plan":`Requires ${FACILITIES[plan.minFacility-1]?.name||`tier ${plan.minFacility}`}`}</button></article>`}).join("")}</div><p class="modal-note" style="margin-top:10px">Dual-SIM represents two independent cellular carriers, not free backup bandwidth. Fibre buys resilience and propagation, while mobile failover sacrifices some block-delivery performance. All prices and incident rates are gameplay models.</p></div></section>`;
}
function energyTariffVisual(){
  const r=region(),fs=fleet(),contract=powerContract(),shock=energyShock(state.time),efficiency=energyEfficiencyFactor(),migration=rateMultiplier(),density=energyLoadFactor(),activeShock=shock!==1||migration!==1,rateFor=c=>r.kwh*c.mult*(c.id==="fixed"?1:shock)*efficiency*migration*density,dailyFor=c=>fs.kw*(c.id==="curtail"?.78:1)*24*rateFor(c);
  return `<section class="card span-12"><div class="card-head"><h2>Energy tariff desk</h2><div class="meta">${activeShock?"LIVE PRICE ADJUSTMENT":"NORMAL MARKET CONDITIONS"}</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">Regional base tariff</div><strong>${fmtUsd(r.kwh)}/kWh</strong><small>${r.name} before contract and skills</small></div><div class="metric"><div class="label">Contract multiplier</div><strong>${contract.mult.toFixed(2)}×</strong><small>${contract.name}</small></div><div class="metric"><div class="label">Efficiency multiplier</div><strong>${efficiency.toFixed(3)}×</strong><small>${hasSkill("metering")||hasSkill("curtailment")?"Tech discount applied":"No energy tech discount"}</small></div><div class="metric"><div class="label">All-in energy rate</div><strong>${fmtUsd(powerRate(r))}/kWh</strong><small>${activeShock?`Market / migration adjustment ${(shock*migration).toFixed(2)}×`:"No active adjustment"}</small></div></div><div class="venue-grid" style="margin-top:12px">${POWER_CONTRACTS.map(c=>{const rate=rateFor(c),selected=c.id===state.contract,shockNote=c.id==="fixed"?"Shielded from historical energy shock":"Exposed to historical energy shock";return `<article class="venue ${selected?"active":""}"><div class="risk ${selected?"low":"medium"}">${selected?"CURRENT CONTRACT":shockNote}</div><h3>${c.name}</h3><p>${c.desc}</p><div class="trade-value">${fmtUsd(rate)}/kWh</div><div class="trade-sub">${fs.kw.toFixed(2)} kW fleet · ${fmtUsd(dailyFor(c))}/day electricity</div><button class="action small ${selected?"":"primary"}" data-action="contract" data-id="${c.id}" ${selected?"disabled":""}>${selected?"Selected":"Use this tariff"}</button></article>`}).join("")}</div><p class="modal-note" style="margin-top:10px">Formula: regional base tariff × contract multiplier × historical energy shock (except fixed PPA) × tech efficiency × any temporary migration repricing. Rent, staff and insurance are separate from this energy rate.</p></div></section>`;
}
function maintenanceVisual(fs){
  const covid=covidPartsMarket(),multiplier=covid?2.25:1,rows=HARDWARE.filter(h=>(state.hardware[h.id]||0)>0).map(h=>{const health=maintenanceCondition(h),reason=hardwareOfflineReason(h),faults=hardwareFaultCount(h),repairCount=health<65?state.hardware[h.id]:Math.max(faults,Math.ceil(state.hardware[h.id]*.15)),requirements=serviceRequirements(h,repairCount),status=activeServiceJob(h.id)?"Repair in progress":reason?reason:faults?`${faults} unexpected fault${faults===1?"":"s"} offline`:"Operating";return `<div class="balance-row"><div class="balance-name">${h.name}<small>${state.hardware[h.id]} units · ${status}</small><div class="bar" style="--w:${health}%;--bar:${health<65||faults?"var(--red)":health<80?"var(--orange)":"var(--green)"}"><i></i></div></div><div class="balance-num"><b>${health.toFixed(0)}%</b><small>${serviceRequirementText(requirements)}</small><button class="action small" data-action="service-hw" data-id="${h.id}" ${hasServiceParts(requirements)?"":"disabled"}>Service ${repairCount}</button></div></div>`}).join("")||`<div class="empty-story">No serviceable mining hardware is installed.</div>`;
  const offline=fs.offline.length?`<p class="forecast-status" style="color:var(--red)">OFFLINE ASSETS: ${fs.offline.map(x=>`${x.n}× ${x.h.name} — ${x.reason}`).join(" · ")}</p>`:"";
  const spares=SPARE_PARTS.map(part=>{const onOrder=state.maintenance.orders.filter(order=>(order.type||"fan")===part.id).reduce((sum,order)=>sum+order.qty,0);return `<article class="venue"><div class="risk low">${state.maintenance.inventory[part.id]||0} IN STOCK</div><h3>${part.name}</h3><p>${part.desc}</p><div class="trade-sub">${onOrder} on order · ${fmtUsd(part.cost*multiplier)} each</div><div class="actions"><button class="action small primary" data-action="order-parts" data-id="${part.id}" data-value="1" ${state.cash<part.cost*multiplier?"disabled":""}>Order 1</button><button class="action small" data-action="order-parts" data-id="${part.id}" data-value="5" ${state.cash<part.cost*multiplier*5?"disabled":""}>Order 5</button><button class="action small" data-action="order-parts" data-id="${part.id}" data-value="50" ${state.cash<part.cost*multiplier*50?"disabled":""}>Order 50</button></div></article>`}).join("");
  return `<section class="card span-12"><div class="card-head"><h2>Fleet maintenance & spares</h2><div class="meta">${covid?"COVID SUPPLY SHOCK · 42-DAY LEAD TIMES":"NORMAL PARTS MARKET · 14-DAY LEAD TIMES"}</div></div><div class="card-pad"><div class="venue-grid">${spares}</div>${offline}<div class="balance-list" style="margin-top:10px">${rows}</div><p class="modal-note">Individual machines can now fail unexpectedly as fleets age and condition falls; only the affected units stop hashing, but repairs need parts and crew time. Condition still creates a fleet-wide maintenance shutdown below 65%. ASIC and hydro fleets need fans, hashboards and power PCBs; hydro equipment also needs coolant components.</p></div></section>`;
}
function operationalRiskVisual(){
  const fwDue=firmwarePatchDue(),hijacked=firmwareHijacked(),outage=siteOutage(),frozen=Object.keys(state.ops.venueFreezes).filter(venueFrozen);
  const firmware=hijacked?"COMPROMISED · 35% of reward diverted until patched":fwDue?"PATCH OVERDUE · exposure rises each month":"CURRENT · signed firmware review complete";
  const incident=activeSiteIncident(),connectivity=incident?`${incident.kind.toUpperCase()} · expected restoration ${dateFmt(incident.until)}`:`${connectivityPlan().name.toUpperCase()} · ${fmtPct(connectivityIncidentRisk()*100)} monthly internet incident chance`;
  return `<section class="card span-12"><div class="card-head"><h2>Operational risk desk</h2><div class="meta">FIRMWARE · GRID · INTERNET · COUNTERPARTIES</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">ASIC firmware</div><strong style="color:${hijacked||fwDue?"var(--red)":"var(--green)"}">${hijacked?"Hijacked":fwDue?"Patch due":"Current"}</strong><small>${firmware}</small></div><div class="metric"><div class="label">Site service</div><strong style="color:${outage?"var(--red)":"var(--green)"}">${incident?incident.kind:"Online"}</strong><small>${connectivity}</small></div><div class="metric"><div class="label">Venue access</div><strong style="color:${frozen.length?"var(--red)":"var(--green)"}">${frozen.length?"Frozen":"Open"}</strong><small>${frozen.length?frozen.map(walletName).join(", "):"No active withdrawal freezes"}</small></div><div class="metric"><div class="label">Mitigation</div><strong>${hasSkill("monitoring")?"Monitored":"Basic"}</strong><small>Monitoring reduces internet incidents by 25%</small></div></div><div class="actions" style="margin-top:14px"><button class="action small ${fwDue||hijacked?"primary":""}" data-action="patch-firmware" ${asicCount()<1||(!fwDue&&!hijacked)?"disabled":""}>${hijacked?"Reflash compromised fleet":fwDue?`Patch ${asicCount()} ASICs · ${fmtUsd(Math.max(75,asicCount()*18))}`:"Firmware current"}</button><button class="action small" data-action="tab" data-value="custody">Review custody exposure</button></div><p class="modal-note" style="margin-top:10px">Grid incidents are driven by regional reliability; internet incidents use jurisdiction risk, your selected connectivity plan and monitoring. Both pause mining and primary-node service while fixed overhead continues.</p></div></section>`;
}
function financeExposureVisual(){
  const eligibleCollateral=fiatCollateral(),collateral=Math.max(1,eligibleCollateral),headroom=projectLoanHeadroom(),loan=state.projectLoan||0,arrears=state.debt||0,total=loan+arrears,monthlyRate=hasStaff("treasurer")?.009:.012,dailyInterest=loan*monthlyRate/30.4375,monthlyInterest=loan*monthlyRate,coverage=loan/collateral,exposureBase=Math.max(eligibleCollateral,total,1),loanPct=loan/exposureBase*100,arrearsPct=arrears/exposureBase*100,risk=arrears>0?"Critical":coverage>.7?"High":coverage>.4?"Elevated":loan>0?"Managed":"None",color=arrears>0?"var(--red)":coverage>.7?"var(--red)":coverage>.4?"var(--orange)":"var(--green)";
  return `<section class="card span-12"><div class="card-head"><h2>Financing exposure</h2><div class="meta" style="color:${color}">${risk.toUpperCase()} RISK</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">Project principal</div><strong>${fmtUsd(loan)}</strong><small>${loan?`${(monthlyRate*100).toFixed(1)}% monthly modelled rate`:"No project loan"}</small></div><div class="metric"><div class="label">Interest / day</div><strong>${fmtUsd(dailyInterest)}</strong><small>${fmtUsd(monthlyInterest)} / month</small></div><div class="metric"><div class="label">Grid arrears</div><strong style="color:${arrears?"var(--red)":"var(--green)"}">${fmtUsd(arrears)}</strong><small>${arrears?"Fleet disconnected until paid":"No unpaid energy bill"}</small></div><div class="metric"><div class="label">New funding capacity</div><strong>${fmtUsd(headroom)}</strong><small>Fiat collateral or six months of recent mining revenue</small></div></div><div class="exposure-strip"><div class="exposure-strip-head"><span>Total exposure: <b>${fmtUsd(total)}</b></span><span>Recent mining revenue: <b>${fmtUsd(state.operator.lastRevenueUsd)}</b></span></div><div class="exposure-track"><i class="exposure-loan" style="width:${loanPct}%"></i><i class="exposure-arrears" style="width:${arrearsPct}%"></i><i class="exposure-empty" style="width:${Math.max(0,100-loanPct-arrearsPct)}%"></i></div><div class="exposure-legend"><span style="--legend:var(--orange)">Project finance ${fmtUsd(loan)}</span><span style="--legend:var(--red)">Grid arrears ${fmtUsd(arrears)}</span><span style="--legend:var(--green)">New funding capacity ${fmtUsd(headroom)}</span></div></div><p class="modal-note" style="margin-top:10px">Operating credit uses the stronger of 50% unborrowed fiat collateral or six months of recent mining revenue. BTC, hardware and securities are not direct collateral. Emergency bridge finance is always more expensive and reduces campaign resilience.</p></div></section>`;
}
function equityPortfolioVisual(){
  const etfBtc=state.wallets.etf||0,etfValue=etfBtc*priceAt(state.time),positions=[...(state.time>=at("2024-01-10")?[{name:"Spot Bitcoin ETF",ticker:"ETF",value:etfValue,detail:`${fmtBtc(etfBtc)} price exposure · not spendable BTC`,active:etfValue>0}]:[]),...STRATEGY_SECURITIES.filter(s=>state.time>=at(s.date)||(state.strategy[s.id]||0)>0).map(s=>{const shares=state.strategy[s.id]||0,value=strategyValue(s.id);return{name:s.name,ticker:s.ticker,value,detail:`${shares.toFixed(2)} shares · ${fmtUsd(strategyPrice(s.id))}/share`,active:value>0}})],total=positions.reduce((sum,p)=>sum+p.value,0);
  if(!positions.length)return"";
  return `<section class="card span-12"><div class="card-head"><h2>Equity portfolio</h2><div class="meta">${fmtUsd(total)} MARKET VALUE · EXCLUDED FROM SELF-CUSTODY SCORE</div></div><div class="card-pad"><div class="venue-grid">${positions.map(position=>`<article class="venue ${position.active?"active":""}"><div class="risk ${position.active?"medium":"low"}">${position.ticker} · ${position.active?"POSITION OPEN":"NO POSITION"}</div><h3>${position.name}</h3><div class="trade-value">${fmtUsd(position.value)}</div><div class="trade-sub">${position.detail}</div></article>`).join("")}</div><p class="modal-note" style="margin-top:10px">Equities and ETF exposure contribute to net worth but are not liquid fiat and do not count as keys-controlled BTC. Buy and sell controls remain in Market.</p></div></section>`;
}
function technicianCrewVisual(){const fs=fleet(),technicians=fieldTechnicianCount(),committed=(state.maintenance.serviceJobs||[]).reduce((sum,job)=>sum+Number(job.crew||0),0),recommended=Math.max(1,Math.ceil(fs.count/80)),wearFactor=technicians?Math.max(.35,.6-.08*Math.min(2,technicians-1)-.02*Math.max(0,technicians-3)):1;return `<section class="card span-12"><div class="card-head"><h2>Field technician crew</h2><div class="meta">SCALABLE OPERATIONS STAFFING</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">On payroll</div><strong>${technicians}</strong><small>${fmtUsd(technicians*1200)}/month</small></div><div class="metric"><div class="label">Assigned now</div><strong>${committed}</strong><small>${Math.max(0,technicians-committed)} available for the next job</small></div><div class="metric"><div class="label">Crew target</div><strong>${recommended}</strong><small>1 technician per ~80 machines</small></div><div class="metric"><div class="label">Wear rate</div><strong>${Math.round(wearFactor*100)}%</strong><small>of the no-technician baseline</small></div></div><p class="modal-note" style="margin-top:10px">A service crew can have up to three technicians on one hardware type. Extra technicians let separate repair jobs run concurrently; one unstaffed operation can still use a slower, 35%-costlier contractor crew.</p></div></section>`}
function operationsStrategyVisual(){
  const done=["coin","uptime","scale","reserve"].filter(id=>state.milestones.includes(id)).length,staffing=staffHiringAvailable(),reserveProgress=reserveMilestoneProgress(),headroom=projectLoanHeadroom(),fundingReason=projectFinanceReason();
  return `<section class="card span-12"><div class="card-head"><h2>Operating strategy</h2><div class="meta">STAFF · FINANCE · INSURANCE</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">Staff burn</div><strong>${fmtUsd(staffMonthlyCost())}/mo</strong><small>${state.staff.length} roles hired</small></div><div class="metric"><div class="label">Project finance</div><strong>${fmtUsd(state.projectLoan)}</strong><small>${state.projectLoan?`${hasStaff("treasurer")?"0.9":"1.2"}% monthly interest`:"no debt"}</small></div><div class="metric"><div class="label">Migration cover</div><strong>${state.insured?"Active":"None"}</strong><small>${state.insured?`${fmtUsd(insuranceMonthlyCost())}/mo premium`:"Optional incident protection"}</small></div><div class="metric"><div class="label">Strategic goals</div><strong>${done} / 4</strong><small>${reserveProgress}</small></div></div><p class="modal-note" style="margin-top:12px">${staffing?`Tier ${facilityTier()} staffing unlocked at ${facility().name}.`:`Staff hiring unlocks after moving into the tier 3 Light industrial unit or any larger facility. Current site: ${facility().name} (tier ${facilityTier()}).`}</p><div class="venue-grid" style="margin-top:12px">${STAFF.map(s=>{const hired=hasStaff(s.id),locked=!staffing&&!hired;return `<article class="venue ${hired?"active":""} ${locked?"locked":""}"><div class="risk ${hired?"low":"medium"}">${locked?"TIER 3 FACILITY REQUIRED":fmtUsd(s.salary)+"/month"}</div><h3>${s.name}</h3><p>${s.desc}</p><button class="action small ${hired||locked?"":"primary"}" data-action="hire-staff" data-id="${s.id}" ${hired||locked?"disabled":""}>${hired?"Hired":locked?"Requires tier 3 facility":"Hire"}</button></article>`}).join("")}</div><div class="actions" style="margin-top:12px"><button class="action small ${state.insured?"primary":""}" data-action="insurance">${state.insured?"Insurance active":"Buy migration insurance"}</button><button class="action small ${headroom>0?"primary":""}" data-action="project-loan" ${headroom<=0?"disabled":""}>${headroom>0?`Draw project finance · up to ${fmtUsd(headroom)}`:"Growth funding unavailable"}</button><button class="action small" data-action="repay-loan" ${state.projectLoan<=0||state.cash<=0?"disabled":""}>Repay project finance</button><span class="label">${fundingReason}</span></div><p class="modal-note" style="margin-top:10px">Migration insurance protects eligible facility-move incidents, not ordinary operating losses. Project finance uses recent mining revenue or unborrowed fiat support; bridge rescue is costlier. Energy tariffs are selected exclusively in the Energy tab.</p></div></section>`;
}
function facilityCommandVisual(){
  const fs=fleet(),power=Math.min(100,fs.cap?fs.kw/fs.cap*100:0),space=Math.min(100,facility().space?fs.space/facility().space*100:0),online=operating();
  return `<section class="card span-12 facility-command"><div class="site-command"><div class="site-copy"><div class="hero-kicker">${narrativeEra().label}</div><h2>${facility().name}</h2><p>${narrativeCopy("facilities")}</p><div class="site-tags"><span>${region().name}</span><span>${region().policy}</span><span>${fs.count} machine${fs.count===1?"":"s"}</span><span>${fmtHash(fs.hash)}</span></div></div><div class="site-illustration">${buildingSvg(state.facility,"site-building")}${flagSvg(state.region,"site-flag")}<span class="site-caption">${fmtUsd(monthlyCost().rate)}/kWh</span><span class="site-status ${online?"":"offline"}">${online?"● fleet hashing":"● fleet offline"}</span><div class="site-bars"><div class="site-bar-label"><span>Power</span><b>${power.toFixed(0)}%</b></div><div class="bar" style="--w:${power}%;--bar:${power>90?"var(--red)":"var(--orange)"}"><i></i></div><div class="site-bar-label"><span>Floor</span><b>${space.toFixed(0)}%</b></div><div class="bar" style="--w:${space}%;--bar:var(--green)"><i></i></div></div></div></div></section>`;
}
function enhanceFacilities(){
  setTimeout(()=>{const riskGrid=document.querySelector(".content .grid");if(riskGrid&&!riskGrid.querySelector(".operational-risk-desk")){const panel=operationalRiskVisual().replace('class="card span-12"','class="card span-12 operational-risk-desk"'),command=riskGrid.querySelector(".facility-command");if(command)command.insertAdjacentHTML("afterend",panel);else riskGrid.insertAdjacentHTML("afterbegin",panel)}},0);
  const grid=document.querySelector(".content .grid"),fs=fleet();if(!grid)return;
  grid.insertAdjacentHTML("afterbegin",financeExposureVisual());
  grid.insertAdjacentHTML("afterbegin",energyTariffVisual());
  grid.insertAdjacentHTML("afterbegin",facilityCommandVisual());
  setTimeout(()=>{const command=grid.querySelector(".facility-command"),risk=grid.querySelector(".operational-risk-desk");if(command)grid.prepend(command);if(command&&risk)command.insertAdjacentElement("afterend",risk)},0);
  grid.insertAdjacentHTML("afterbegin",`${operationsStrategyVisual()}${maintenanceVisual(fs)}${settlementForecastVisual()}<section class="card span-12"><div class="card-head"><h2>Operations map</h2><div class="meta">LIVE FACILITY & FLEET VIEW</div></div><div class="ops-map"><div class="ops-tile"><h3>${facility().name}</h3><p>${fs.kw.toFixed(1)} / ${fs.cap.toFixed(1)} kW · ${fs.space} / ${facility().space} floor units</p>${buildingSvg(state.facility,"ops-building")}</div><div class="ops-tile"><h3>${region().name}</h3>${flagSvg(state.region,"ops-flag")}<p style="text-align:center">${region().policy}</p></div><div class="ops-tile"><h3>${fs.count} machines</h3>${fleetSvg(fs)}<p style="text-align:center">${fmtHash(fs.hash)} deployed</p></div></div></section>`);
  document.querySelectorAll('[data-action="facility"]').forEach(button=>{const risk=facilityMoveRisk(button.dataset.id),card=button.parentElement;card.insertAdjacentHTML("afterbegin",buildingSvg(button.dataset.id));if(!risk)return;const info=document.createElement("div");info.className="trade-sub";info.textContent=`${facilityRiskLabel(risk)} · ${Math.round(risk*100)}% incident chance · contract, transit or seizure`;card.insertBefore(info,button);});
  document.querySelectorAll('[data-action="region"]').forEach(button=>button.parentElement.insertAdjacentHTML("afterbegin",flagSvg(button.dataset.id)));
  document.querySelectorAll('[data-action="service-hw"]').forEach(button=>{const h=HARDWARE.find(x=>x.id===button.dataset.id),job=activeServiceJob(button.dataset.id);if(!h)return;if(job){button.disabled=true;button.textContent=`In service · ${Math.max(0,Math.ceil((job.due-state.time)/DAY))}d`}else{const plan=servicePlan(h,state.hardware[h.id]||0);button.textContent=`Service · ${plan.days}d`;if(maintenanceCondition(h)>=95){button.disabled=true;button.title="Service is only needed below 95% condition"}}});
}
function enhanceFacilitiesV2(){
  const grid=document.querySelector(".content .grid"),fs=fleet();if(!grid)return;
  const facilityOptions=grid.querySelector(".facility-options");
  grid.insertAdjacentHTML("afterbegin",facilityCommandVisual());
  grid.insertAdjacentHTML("afterbegin",`${settlementForecastVisual()}${connectivityPlansVisual()}${maintenanceVisual(fs)}<section class="card span-12"><div class="card-head"><h2>Operations map</h2><div class="meta">LIVE FACILITY & FLEET VIEW</div></div><div class="ops-map"><div class="ops-tile"><h3>${facility().name}</h3><p>${fs.kw.toFixed(1)} / ${fs.cap.toFixed(1)} kW · ${fs.space} / ${facility().space} floor units</p>${buildingSvg(state.facility,"ops-building")}</div><div class="ops-tile"><h3>${region().name}</h3>${flagSvg(state.region,"ops-flag")}<p style="text-align:center">${region().policy}</p></div><div class="ops-tile"><h3>${fs.count} machines</h3>${fleetSvg(fs)}<p style="text-align:center">${fmtHash(fs.hash)} deployed</p></div></div></section>`);
  const command=grid.querySelector(".facility-command");if(command)grid.prepend(command);
  if(command&&facilityOptions)command.insertAdjacentElement("afterend",facilityOptions);
  setTimeout(()=>{if(!grid.querySelector(".operational-risk-desk")){const panel=operationalRiskVisual().replace('class="card span-12"','class="card span-12 operational-risk-desk"');if(facilityOptions)facilityOptions.insertAdjacentHTML("afterend",panel);else if(command)command.insertAdjacentHTML("afterend",panel);else grid.insertAdjacentHTML("afterbegin",panel)}},0);
  document.querySelectorAll('[data-action="facility"]').forEach(button=>{const risk=facilityMoveRisk(button.dataset.id),card=button.parentElement;card.insertAdjacentHTML("afterbegin",buildingSvg(button.dataset.id));if(!risk)return;const info=document.createElement("div");info.className="trade-sub";info.textContent=`${facilityRiskLabel(risk)} · ${Math.round(risk*100)}% incident chance · contract, transit or seizure`;card.insertBefore(info,button);});
  document.querySelectorAll('[data-action="region"]').forEach(button=>button.parentElement.insertAdjacentHTML("afterbegin",flagSvg(button.dataset.id)));
}
function energyCommandVisual(){const fs=fleet(),rate=powerRate(region()),daily=fs.kw*24*rate;return `<section class="card span-12"><div class="tab-command"><div class="tab-command-copy"><div class="hero-kicker">${narrativeEra().label}</div><h2>Energy flow</h2><p>${narrativeCopy("energy")}</p><div class="tab-command-stats"><span><b>${fs.kw.toFixed(2)} kW</b> fleet load</span><span><b>${fmtUsd(rate)}/kWh</b> all-in rate</span><span><b>${fmtUsd(daily)}</b> electricity / day</span></div></div><div class="tab-command-art"><svg class="tab-art" viewBox="0 0 360 165" aria-label="Electricity flowing to mining fleet"><path d="M42 130h280" stroke="#53615e" stroke-width="3"/><path d="M81 125V43l26-25 26 25v82M229 125V52l22-17 22 17v73" fill="#172628" stroke="#86c79a" stroke-width="3"/><path d="M107 43v-17M95 26h24M251 52V32M240 32h22" stroke="#f0a92f" stroke-width="3"/><path d="M134 86h92" stroke="#f0a92f" stroke-width="5" stroke-dasharray="9 7"/><path d="M175 62l-13 25h17l-9 24 29-33h-17l10-16z" fill="#ffc267"/><circle class="glow" cx="214" cy="86" r="4"/><path d="M237 111h28M237 101h28M237 91h28" stroke="#86c79a" stroke-width="3"/></svg></div></div></section>`}
function enhanceEnergy(){const grid=document.querySelector(".content .grid");if(!grid)return;const energyCapital=grid.firstElementChild;grid.insertAdjacentHTML("afterbegin",energyCommandVisual());const command=grid.firstElementChild;if(command&&energyCapital)command.insertAdjacentElement("afterend",energyCapital);grid.insertAdjacentHTML("beforeend",`${energyTariffVisual()}${connectivityPlansVisual()}${settlementForecastVisual()}`)}
function enhanceFinance(){
  const grid=document.querySelector(".content .grid");if(!grid)return;grid.insertAdjacentHTML("afterbegin",`${narrativeBanner("finance","Capital through the cycle")}${treasuryPolicyVisual()}${operatorScoreVisual()}${financeExposureVisual()}${operationsStrategyVisual()}`);grid.insertAdjacentHTML("beforeend",`${settlementForecastVisual()}${technicianCrewVisual()}${equityPortfolioVisual()}`);
  const fundingMetric=[...grid.querySelectorAll(".metric")].find(metric=>metric.querySelector(".label")?.textContent==="New funding capacity"),fundingDetail=fundingMetric?.querySelector("small");if(fundingDetail&&state.time<PROJECT_FINANCE_START)fundingDetail.textContent=`Unlocks ${dateFmt(PROJECT_FINANCE_START,true)} when industrial mining credit emerges`;
  const fieldTechButton=grid.querySelector('[data-action="hire-staff"][data-id="fieldtech"]');if(fieldTechButton){const staffing=staffHiringAvailable();fieldTechButton.disabled=!staffing;fieldTechButton.textContent=staffing?`Hire technician #${fieldTechnicianCount()+1}`:"Requires tier 3 facility";fieldTechButton.closest(".venue")?.querySelector(".risk")?.replaceChildren(document.createTextNode(staffing?`${fmtUsd(1200)}/month · ${fieldTechnicianCount()} on payroll`:"TIER 3 FACILITY REQUIRED"));}
}
