"use strict";

function custody(){
  const nodeCopy=state.node===0?"Bitcoin Core runs on the Basic laptop and validates the chain independently while that machine is powered and healthy. Shut the mining laptop down and live verification pauses until it returns and catches up.":state.node===1?"A dedicated full-node appliance stays powered when the mining fleet is manually shut down. Connectivity, storage and account failures can still interrupt it or leave it behind the chain tip.":"Hardened local storage, monitoring and relay infrastructure improve synchronization, propagation and treasury operations.";
  return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Keys, claims and verification</div><h1>Bitcoin is on the ledger. Control lives in the keys.</h1><p>A node verifies rules; keys control coins; an exchange or ETF remains a claim on someone else. Keep those distinctions visible as the ecosystem grows.</p></div><div class="hero-stat"><strong>${fmtBtc(controlled())}</strong><span>BTC controlled by your keys</span></div></div></section>
    <section class="card span-5"><div class="card-head"><h2>Your node</h2><div class="meta">${nodeDeploymentName().toUpperCase()}</div></div><div class="card-pad"><p style="color:var(--muted);line-height:1.6">${nodeCopy}</p><div class="actions"><button class="action primary" data-action="buy-node" data-value="1" ${state.node>=1||state.cash<260?"disabled":""}>Dedicated full node · $260</button><button class="action" data-action="buy-node" data-value="2" ${state.node>=2||state.time<at("2016-01-01")||state.cash<1200?"disabled":""}>Hardened node · $1,200</button></div><div class="metric-row" style="margin:18px -16px -16px"><div class="metric"><div class="label">Verified days</div><strong>${fmtNum(state.nodeDays)}</strong><small>At least one node was at tip</small></div><div class="metric"><div class="label">Live verification</div><strong style="color:${nodeOnline()?"var(--green)":"var(--red)"}">${nodeOnline()?"ONLINE":"OFFLINE"}</strong><small>${nodeVerificationPath()}</small></div></div></div></section>
    <section class="card span-7"><div class="card-head"><h2>Wallet allocation</h2><div class="meta">calculated</div></div><div class="balance-list">${btcBreakdown()}</div></section>
    <section class="card span-12"><div class="card-head"><h2>Self-custody actions</h2></div><div class="card-pad actions"><button class="action" data-action="transfer" data-from="hot" data-to="cold" data-value=".25" ${!venueAvailable("cold")||state.wallets.hot<=0?"disabled":""}>Move 25% hot → cold</button><button class="action" data-action="transfer" data-from="cold" data-to="hot" data-value=".25" ${state.wallets.cold<=0?"disabled":""}>Move 25% cold → hot</button><span class="push label">${venueAvailable("cold")?"Cold storage available":"Cold storage practices unlock in 2012"}</span></div></section></div>`
}
function facilities(){
  const fs=fleet(),mc=monthlyCost();return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Power and place</div><h1>${region().name} · ${facility().name}</h1><p>Cheap electricity is useful only while the grid, law and internet remain available. Compare capacity, reliability and the full cost of moving.</p></div><div class="hero-stat"><strong>${fmtUsd(mc.total)}/mo</strong><span>${fmtUsd(mc.rate)}/kWh · ${(region().rely*100).toFixed(1)}% base uptime</span></div></div><div class="metric-row"><div class="metric"><div class="label">Electrical load</div><strong>${fs.kw.toFixed(2)} / ${fs.cap.toFixed(1)} kW</strong></div><div class="metric"><div class="label">Floor load</div><strong>${fs.space} / ${facility().space}</strong></div><div class="metric"><div class="label">Accrued bill</div><strong>${fmtUsd(state.bill)}</strong></div><div class="metric"><div class="label">Grid state</div><strong style="color:${operating()?"var(--green)":"var(--red)"}">${operating()?"ONLINE":"OFFLINE"}</strong></div></div></section>
    <section class="span-12 facility-grid facility-options">${FACILITIES.filter(f=>f.id===state.facility||announced(f)).sort((a,b)=>(b.id===state.facility)-(a.id===state.facility)||at(a.date)-at(b.date)).map(f=>{const available=state.time>=at(f.date),active=f.id===state.facility;return `<article class="facility ${active?"active":""} ${available?"":"locked"}"><div class="risk ${active?"low":"medium"}">${active?"Current site":available?"Available":dateFmt(at(f.date),true)}</div><h3>${f.name}</h3><p>${f.desc}</p><div class="facility-stats"><span>${fmtNum(f.kw)} kW</span><span>${fmtNum(f.space)} space</span><span>${fmtUsd(f.rent)}/mo</span></div><button class="action small ${active?"":"primary"}" data-action="facility" data-id="${f.id}" ${active||!available||state.cash<(f.cost+facilityReserve(f))?"disabled":""}>${active?"Operating here":"Fit out · "+fmtUsd(f.cost)}${!active&&available?` · reserve ${fmtUsd(facilityReserve(f))}`:""}</button></article>`}).join("")}</section>
    <section class="card span-12"><div class="card-head"><h2>Jurisdiction, grid & internet</h2><div class="meta">relocation includes 5% of fleet value</div></div><div class="card-pad facility-grid">${REGIONS.filter(r=>r.id===state.region||announced(r)).map(r=>{const closed=r.id==="sichuan"&&state.time>=at("2021-06-21"),available=state.time>=at(r.date)&&!closed,active=r.id===state.region,cost=(r.move+fs.value*.05)*(hasSkill("relocation")?.8:1)*(hasStaff("logistics")?.8:1);return `<article class="facility ${active?"active":""}"><div class="risk ${closed?"high":r.rely>.98?"low":r.rely>.93?"medium":"high"}">${closed?"Mining prohibited":r.policy}</div><h3>${r.name}</h3><p>${r.desc}</p><div class="facility-stats"><span>${fmtUsd(r.kwh)}/kWh</span><span>${(r.rely*100).toFixed(1)}% grid uptime</span><span>${fmtUsd(r.internet||75)}/mo internet base</span></div><button class="action small" data-action="region" data-id="${r.id}" ${active||!available||state.cash<cost?"disabled":""}>${active?"Current region":closed?"Closed after crackdown":available?"Relocate · "+fmtUsd(cost):"Unlocks "+dateFmt(at(r.date),true)}</button></article>`}).join("")}</div></section></div>`
}
function energy(){
  const fs=fleet(),rate=powerRate(region()),daily=dailyEnergyCostForWatts(fs.w*contractLoadFactor());return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Energy economics</div><h1>Price the electrons before you price the fleet.</h1><p>Choose a tariff, understand utilisation and shock exposure, and keep enough liquid fiat for the next settlement.</p></div><div class="hero-stat"><strong>${fmtUsd(rate)}/kWh</strong><span>${fmtUsd(daily)}/day at current fleet load</span></div></div><div class="metric-row"><div class="metric"><div class="label">Base tariff</div><strong>${fmtUsd(region().kwh)}/kWh</strong><small>${region().name}</small></div><div class="metric"><div class="label">Selected contract</div><strong>${powerContract().name}</strong><small>${powerContract().mult.toFixed(2)}× multiplier</small></div><div class="metric"><div class="label">Fleet draw</div><strong>${fs.kw.toFixed(2)} kW</strong><small>Active mining hardware</small></div><div class="metric"><div class="label">Accrued bill</div><strong>${fmtUsd(state.bill)}</strong><small>Settles monthly</small></div></div></section></div>`
}
function finance(){
  const loan=state.projectLoan||0,arrears=state.debt||0,rate=hasStaff("treasurer")?.009:.012,daily=loan*rate/30.4375;return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Capital structure</div><h1>Fund growth without losing operating control.</h1><p>Project finance accelerates expansion, but interest consumes liquid fiat. A profitable mining record now creates borrowing capacity alongside cash collateral.</p></div><div class="hero-stat"><strong>${fmtUsd(loan+arrears)}</strong><span>total financing & arrears exposure</span></div></div><div class="metric-row"><div class="metric"><div class="label">Project loan</div><strong>${fmtUsd(loan)}</strong><small>${(rate*100).toFixed(1)}% monthly rate</small></div><div class="metric"><div class="label">Interest / day</div><strong>${fmtUsd(daily)}</strong><small>Accrues at monthly settlement</small></div><div class="metric"><div class="label">Grid arrears</div><strong>${fmtUsd(arrears)}</strong><small>${arrears?"Fleet currently disconnected":"No overdue bill"}</small></div><div class="metric"><div class="label">Liquid cash</div><strong>${fmtUsd(state.cash)}</strong><small>Available for repayment</small></div></div></section></div>`
}
function tech(){
  return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Operator specialisation</div><h1>Spend knowledge where your strategy lives.</h1><p>Major historical events and mining milestones grant points. Higher tiers require the previous skill in their branch.</p></div><div class="hero-stat"><strong>${state.points}</strong><span>unspent skill points</span></div></div></section><section class="span-12 skill-grid">${SKILLS.map(s=>{const unlocked=hasSkill(s.id),ready=!s.req||hasSkill(s.req),enough=state.points>=s.cost;const reason=unlocked?"Unlocked":!ready?`Requires ${SKILLS.find(x=>x.id===s.req).name}`:!enough?`Need ${s.cost} point${s.cost===1?"":"s"} · you have ${state.points}`:"Ready to unlock";return `<article class="skill ${unlocked?"unlocked":""}"><div class="skill-branch">${s.branch}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="skill-lock"><div class="skill-reason">${reason}</div><button class="action small ${unlocked?"":"primary"}" data-action="skill" data-id="${s.id}" ${unlocked||!ready||!enough?"disabled":""}>${unlocked?"Unlocked":`${s.cost} point${s.cost===1?"":"s"}`}</button></div></article>`}).join("")}</section></div>`
}
function learn(){
  const active=learningItem(),progress=active?Math.min(100,Math.round((state.learning.progress||0)/active.days*100)):0;
  return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Operator learning</div><h1>Knowledge compounds, one commitment at a time.</h1><p>Only one item progresses at a time. Every three knowledge unlocks a skill point that can reshape the underlying operation.</p></div><div class="hero-stat"><strong>${state.knowledge.toFixed(1)}</strong><span>knowledge · next skill at ${state.nextKnowledge}</span></div></div>${active?`<div class="metric-row"><div class="metric"><div class="label">Active learning</div><strong>${active.title}</strong><small>${active.type} · ${active.author}</small></div><div class="metric"><div class="label">Progress</div><strong id="learning-progress-days">${state.learning.progress||0} / ${active.days} days</strong><small id="learning-progress-percent">${progress}% complete</small></div><div class="metric"><div class="label">Reward</div><strong>${active.reward} knowledge</strong><small>${active.check?"Includes a knowledge check":"Completes automatically"}</small></div><div class="metric"><div class="label">Learning slot</div><strong>Occupied</strong><small>Finish this before choosing another</small></div></div>`:"<div class=\"metric-row\"><div class=\"metric\"><div class=\"label\">Learning slot</div><strong>Available</strong><small>Choose a book or podcast</small></div><div class=\"metric\"><div class=\"label\">Knowledge cadence</div><strong>3 = 1 point</strong><small>For the Tech skill tree</small></div></div>"}</section>${active&&state.learning.waiting?`<section class="card span-12"><div class="card-head"><h2>Knowledge check</h2><div class="meta">FULL REWARD IF CORRECT · 60% OTHERWISE</div></div><div class="card-pad"><p style="color:var(--muted);line-height:1.6">${active.check.q}</p><div class="actions">${active.check.options.map((answer,i)=>`<button class="action ${i===0?"primary":""}" data-action="learning-check" data-value="${i}">${answer}</button>`).join("")}</div></div></section>`:""}<section class="span-12 venue-grid">${LEARNING.filter(item=>state.completedLearning.includes(item.id)||state.learning?.id===item.id||announced(item)).map(item=>{const available=state.time>=at(item.date),done=state.completedLearning.includes(item.id),busy=!!active;return `<article class="venue ${done?"active":""} ${available?"":"locked"}"><div class="risk ${item.type==="Book"?"low":"medium"}">${item.type} · ${item.days} simulation days · ${item.reward} knowledge</div><h3>${item.title}</h3><p>${item.desc}</p><div class="trade-sub">${item.author}${item.check?" · knowledge check at completion":""}</div><button class="action small ${done?"":"primary"}" data-action="start-learning" data-id="${item.id}" ${!available||done||busy?"disabled":""}>${done?"Completed":!available?`Unlocks ${dateFmt(at(item.date),true)}`:busy?"Learning slot occupied":item.type==="Podcast"?"Subscribe & listen":"Start reading"}</button></article>`}).join("")}</section></div>`
}
