"use strict";

function poolExplorerBody(t){
  const net=hashAt(t),rows=POOLS.filter(p=>p.id!=="solo"&&p.id!=="other"&&t>=at(p.date)).map(p=>({p,share:poolShareAt(p.id,t)})).filter(x=>x.share>.0005).sort((a,b)=>b.share-a.share),named=rows.reduce((sum,x)=>sum+x.share,0),other=Math.max(0,1-named),shares=[...rows.map(x=>x.share),other].filter(Boolean),hhi=shares.reduce((sum,x)=>sum+x*x,0),top=rows[0],concentration=!top?"No public pools":top.share>=.4?"Critical concentration":top.share>=.25?"High concentration":top.share>=.15?"Competitive field":"Diffuse network",selectedShare=state.mode==="pool"?poolShareAt(state.pool,t):0,colors=["#f0a92f","#86c79a","#79c8d3","#b9a4ce","#e78270","#d5b26e","#7aa6b8","#9385a5"];
  if(!rows.length)return `<div class="pool-era-empty"><b>No public mining pool exists yet.</b><span>Block discovery is entirely solo. Move the timeline forward to December 2010 to see pooled variance reduction emerge.</span></div>`;
  return `<div class="pool-era-summary"><div><span>Network hashrate</span><b>${fmtHash(net)}</b></div><div><span>Largest pool</span><b>${top.p.name} · ${(top.share*100).toFixed(1)}%</b></div><div><span>Concentration index</span><b>${Math.round(hhi*10000)} HHI</b></div><div><span>Readout</span><b class="${top.share>=.4?"profit-negative":top.share>=.25?"profit-neutral":"profit-positive"}">${concentration}</b></div></div><div class="pool-bars">${rows.map((x,i)=>`<div class="pool-bar-row ${state.mode==="pool"&&state.pool===x.p.id?"selected":""}"><span>${x.p.name}</span><div><i style="--pool-width:${Math.min(100,x.share*100)}%;--pool-color:${colors[i%colors.length]}"></i></div><b>${(x.share*100).toFixed(1)}%</b><small>${fmtHash(net*x.share)} · ~${(144*x.share).toFixed(1)} blocks/day</small></div>`).join("")}<div class="pool-bar-row other"><span>Other / solo</span><div><i style="--pool-width:${Math.min(100,other*100)}%;--pool-color:#40504d"></i></div><b>${(other*100).toFixed(1)}%</b><small>${fmtHash(net*other)} estimated</small></div></div><div class="pool-era-foot"><span>Your current method at this date: <b>${state.mode==="solo"?"Solo":`${poolData().name} · ${(selectedShare*100).toFixed(1)}% of blocks`}</b></span><span>HHI rises as hash becomes concentrated in fewer pools.</span></div>`
}
function poolHistoryExplorer(){
  const min=START,max=Math.max(START+DAY,state.time);return `<section class="card span-12 pool-explorer"><div class="card-head"><h2>Explore the hash market</h2><div class="meta">DRAG THROUGH POOL HISTORY</div></div><div class="card-pad"><div class="pool-time-control"><div><span>Historical snapshot</span><output id="pool-history-date">${dateFmt(state.time,true)}</output></div><input type="range" min="${min}" max="${max}" step="${DAY*30}" value="${state.time}" data-pool-history aria-label="Explore mining pool history"><div><span>${dateFmt(min,true)}</span><span>${dateFmt(max,true)}</span></div></div><div id="pool-explorer-body">${poolExplorerBody(state.time)}</div><p class="modal-note">This explorer is read-only: it lets you inspect historical pool share and estimated hash without moving the game clock. Shares are smoothed between stored anchors; block counts are share × the 144-block daily target.</p></div></section>`
}
function updatePoolExplorer(t){const clamped=Math.max(START,Math.min(state.time,Number(t)||state.time)),output=document.getElementById("pool-history-date"),body=document.getElementById("pool-explorer-body");if(output)output.textContent=dateFmt(clamped,true);if(body)body.innerHTML=poolExplorerBody(clamped)}
function pools(){
  const selected=state.mode==="pool"?poolData():null,fs=fleet(),eligible=POOLS.filter(p=>p.id!=="solo"&&p.id!=="other"&&state.time>=at(p.date)&&poolEligible(p));
  const expected=operating()?expectedDay():0,fee=selected?poolFee():0,netReward=expected*(1-fee);
  return `<div class="grid">
    <section class="card span-12"><div class="hero"><div><div class="hero-kicker">Payout method & network coordination</div><h1>${selected?selected.name:"Solo mining"}</h1><p>Choose how block-finding variance is handled, compare pool fees and watch concentration change through Bitcoin history. Pool selection changes payout smoothing and fees, not your physical hashrate.</p></div><div class="hero-stat"><strong>${fmtBtc(netReward)}</strong><span>expected net BTC / day</span></div></div><div class="metric-row"><div class="metric"><div class="label">Mining method</div><strong>${state.mode==="solo"?"Solo":"Pool"}</strong><small>${state.mode==="solo"?"High variance · no fee":"Smoothed payouts"}</small></div><div class="metric"><div class="label">Selected fee</div><strong>${(fee*100).toFixed(2)}%</strong><small>${selected?.name||"No pool fee"}</small></div><div class="metric"><div class="label">Eligible pools</div><strong>${eligible.length}</strong><small>Available to this operation now</small></div><div class="metric"><div class="label">Your physical hash</div><strong>${fmtHash(fs.hash)}</strong><small>Unchanged by payout method</small></div></div></section>
    ${poolHistoryExplorer()}
    <section class="card span-12"><div class="card-head"><h2>Choose payout method</h2><div class="meta">SOLO OR ONE ACTIVE POOL</div></div><div class="card-pad pool-method-grid"><article class="venue ${state.mode==="solo"?"active":""}"><div class="risk high">HIGH VARIANCE · 0% FEE</div><h3>Solo mining</h3><p>Keep the full reward when your fleet finds a block, but accept potentially long dry spells.</p><button class="action small ${state.mode==="solo"?"":"primary"}" data-action="mode" data-value="solo" ${state.mode==="solo"?"disabled":""}>${state.mode==="solo"?"Current method":"Switch to solo"}</button></article>${eligible.map(p=>`<article class="venue ${state.mode==="pool"&&state.pool===p.id?"active":""}"><div class="risk medium">${(Math.max(0,p.fee-(hasSkill("poolops")?.004:0))*100).toFixed(2)}% EFFECTIVE FEE</div><h3>${p.name}</h3><p>${p.desc||"Historical mining pool with modelled payout smoothing and fee economics."}</p><button class="action small ${state.mode==="pool"&&state.pool===p.id?"":"primary"}" data-action="pool" data-value="${p.id}" ${state.mode==="pool"&&state.pool===p.id?"disabled":""}>${state.mode==="pool"&&state.pool===p.id?"Current pool":"Mine with this pool"}</button></article>`).join("")}</div></section>
    ${poolDashboard()}
    ${networkShareCard()}
  </div>`
}
