"use strict";

function pools(){
  const selected=state.mode==="pool"?poolData():null,fs=fleet(),eligible=POOLS.filter(p=>p.id!=="solo"&&p.id!=="other"&&state.time>=at(p.date)&&poolEligible(p));
  const expected=operating()?expectedDay():0,fee=selected?poolFee():0,netReward=expected*(1-fee);
  return `<div class="grid">
    <section class="card span-12"><div class="hero"><div><div class="hero-kicker">Payout method & network coordination</div><h1>${selected?selected.name:"Solo mining"}</h1><p>Choose how block-finding variance is handled, compare pool fees and watch concentration change through Bitcoin history. Pool selection changes payout smoothing and fees, not your physical hashrate.</p></div><div class="hero-stat"><strong>${fmtBtc(netReward)}</strong><span>expected net BTC / day</span></div></div><div class="metric-row"><div class="metric"><div class="label">Mining method</div><strong>${state.mode==="solo"?"Solo":"Pool"}</strong><small>${state.mode==="solo"?"High variance · no fee":"Smoothed payouts"}</small></div><div class="metric"><div class="label">Selected fee</div><strong>${(fee*100).toFixed(2)}%</strong><small>${selected?.name||"No pool fee"}</small></div><div class="metric"><div class="label">Eligible pools</div><strong>${eligible.length}</strong><small>Available to this operation now</small></div><div class="metric"><div class="label">Your physical hash</div><strong>${fmtHash(fs.hash)}</strong><small>Unchanged by payout method</small></div></div></section>
    <section class="card span-12"><div class="card-head"><h2>Choose payout method</h2><div class="meta">SOLO OR ONE ACTIVE POOL</div></div><div class="card-pad pool-method-grid"><article class="venue ${state.mode==="solo"?"active":""}"><div class="risk high">HIGH VARIANCE · 0% FEE</div><h3>Solo mining</h3><p>Keep the full reward when your fleet finds a block, but accept potentially long dry spells.</p><button class="action small ${state.mode==="solo"?"":"primary"}" data-action="mode" data-value="solo" ${state.mode==="solo"?"disabled":""}>${state.mode==="solo"?"Current method":"Switch to solo"}</button></article>${eligible.map(p=>`<article class="venue ${state.mode==="pool"&&state.pool===p.id?"active":""}"><div class="risk medium">${(Math.max(0,p.fee-(hasSkill("poolops")?.004:0))*100).toFixed(2)}% EFFECTIVE FEE</div><h3>${p.name}</h3><p>${p.desc||"Historical mining pool with modelled payout smoothing and fee economics."}</p><button class="action small ${state.mode==="pool"&&state.pool===p.id?"":"primary"}" data-action="pool" data-value="${p.id}" ${state.mode==="pool"&&state.pool===p.id?"disabled":""}>${state.mode==="pool"&&state.pool===p.id?"Current pool":"Mine with this pool"}</button></article>`).join("")}</div></section>
    ${poolDashboard()}
    ${networkShareCard()}
  </div>`
}
