"use strict";

/* HISTORICAL LAYER — interpolation and protocol rules are isolated for easy replacement. */
const ANCHOR_TIMES=new WeakMap();
function anchorTime(anchor){let value=ANCHOR_TIMES.get(anchor);if(value===undefined){value=at(anchor[0]);ANCHOR_TIMES.set(anchor,value)}return value}
function upperAnchorIndex(list,time){let low=1,high=list.length-1;while(low<high){const mid=(low+high)>>1;if(anchorTime(list[mid])<time)low=mid+1;else high=mid}return low}
function interp(list,time,log=true){
  if(time<=anchorTime(list[0]))return list[0][1];
  if(time>=anchorTime(list[list.length-1]))return list[list.length-1][1];
  const i=upperAnchorIndex(list,time),a=list[i-1],b=list[i],ta=anchorTime(a),tb=anchorTime(b),t=(time-ta)/(tb-ta);
  return log&&a[1]>0&&b[1]>0?Math.exp(Math.log(a[1])+(Math.log(b[1])-Math.log(a[1]))*t):a[1]+(b[1]-a[1])*t;
}
function stepAt(list,time){if(time<=anchorTime(list[0]))return list[0][1];if(time>=anchorTime(list[list.length-1]))return list[list.length-1][1];const i=upperAnchorIndex(list,time);return anchorTime(list[i])===time?list[i][1]:list[i-1][1]}
const priceAt=t=>interp(PRICE,t),hashAt=t=>interp(HASH,t),txAt=t=>Math.round(interp(TX,t)),heightAt=t=>HEIGHT.length?interp(HEIGHT,t,false):Math.max(0,(t-GENESIS)/DAY*144);
const difficultyAt=t=>DIFFICULTY.length?stepAt(DIFFICULTY,t):hashAt(t)*600/2**32;
const targetHashAt=t=>difficultyAt(t)*2**32/600;
function competitiveHashAt(t,playerHash=0){const historicalFloor=Math.max(hashAt(t),targetHashAt(t))*interp(NETWORK_COMPETITION_SCALE,t,false),responsiveFloor=Math.max(0,playerHash)*interp(NETWORK_RESPONSE,t,false);return Math.max(historicalFloor,responsiveFloor)}
function playerNetworkShareAt(t,playerHash){const competition=competitiveHashAt(t,playerHash);return playerHash>0?playerHash/(competition+playerHash):0}
function expectedBlocksPerDayForHash(hash,t=START){if(hash<=0)return 0;const recorded=hash*86400/(Math.max(1,difficultyAt(t))*2**32),competitionCap=144*playerNetworkShareAt(t,hash);return Math.min(recorded,competitionCap)}
function approxHeight(t){return Math.max(0,Math.floor(heightAt(t)))}
const chainSizeAt=t=>interp(CHAIN_GB,t,false);
const FUTURE_HALVING_INTERVAL=210000*600*1000;
function subsidyHalvingIndex(t){if(t<at("2012-11-28"))return 0;if(t<at("2016-07-09"))return 1;if(t<at("2020-05-11"))return 2;if(t<at("2024-04-19"))return 3;return 4+Math.floor((t-at("2024-04-19"))/FUTURE_HALVING_INTERVAL)}
function subsidyAt(t){return 50/2**subsidyHalvingIndex(t)}
function feeAt(t){return FEES.length?Math.max(0,interp(FEES,t,false)):t<at("2013-01-01")?.02:t<at("2017-01-01")?.15:t<at("2020-01-01")?.35:t<at("2023-01-01")?.22:.45}
function eraAt(t){return t<at("2011-01-01")?"The CPU frontier":t<at("2013-01-01")?"The GPU arms race":t<at("2017-01-01")?"ASIC industrialisation":t<at("2020-01-01")?"Global speculation":t<at("2024-01-01")?"Macro asset, sovereign question":"Institutional & geopolitical era"}
const NARRATIVE_ERAS=[
  {until:"2011-01-01",label:"An unknown experiment",copy:{dashboard:"A few strangers are testing whether money can exist without an issuer. The network is fragile, liquidity is almost nonexistent, and every block you find materially helps it survive.",mine:"Mining is still a hobbyist act of participation. Ordinary processors secure a network whose value is an idea rather than a market price.",market:"There is barely a market to observe. Bitcoin moves through forum trades and informal experiments, so conviction matters long before liquidity exists.",custody:"At this stage Bitcoin is mostly keys, software and personal responsibility. Losing a wallet can matter more than any market movement.",facilities:"Your infrastructure is a desk, a wall socket and an internet connection. Reliability is personal, not industrial.",energy:"Electricity is cheap in absolute terms because the network is tiny, but energy is already the bridge between digital rules and physical cost.",finance:"No lender understands this activity yet. Growth comes from personal fiat, mined coins and a willingness to fund an unproven protocol.",learn:"There is no established canon—only the whitepaper, source code and conversations among early participants trying to discover what they have built.",tech:"Every operational improvement is improvised. The useful advantage is understanding the system before specialised industries form around it."}},
  {until:"2014-01-01",label:"Price discovery and the first arms race",copy:{dashboard:"Bitcoin has acquired a price and a growing community, but remains experimental, volatile and easy to dismiss. GPUs, pools and early exchanges begin turning participation into an industry.",mine:"GPU and FPGA miners professionalise the first hardware race. Hashrate is growing faster than most operators can reinvest, making efficiency a survival question.",market:"A quoted price creates opportunity and fragility at once. Early exchanges make bitcoin liquid enough to trade while concentrating keys in institutions that may not endure.",custody:"As coins become valuable, custody failures stop being theoretical. The distinction between controlling keys and holding an exchange claim becomes financially consequential.",facilities:"Heat, noise and circuit limits push mining out of bedrooms. The operation begins to need deliberate ventilation, wiring and a place in the physical world.",energy:"Power cost starts separating profitable miners from enthusiastic amateurs. A few cents per kilowatt-hour can decide who survives the next difficulty increase.",finance:"Bitcoin can now be sold for working capital, but credit remains scarce and counterparties are primitive. Treasury discipline matters more than financial engineering.",learn:"Forums are documenting attacks, mistakes and new business models in real time. Learning quickly can prevent expensive lessons from being learned through loss.",tech:"Pools, GPUs and early custody practices create the first real operating playbooks. Technical competence is becoming an economic moat."}},
  {until:"2017-01-01",label:"Industrialisation and hard lessons",copy:{dashboard:"ASICs, exchange failures and a rising global network have ended the innocence of the hobby era. Bitcoin survives institutional collapse by continuing to produce valid blocks.",mine:"Purpose-built silicon makes yesterday's hardware obsolete with brutal speed. Mining is becoming a capital-intensive competition in procurement, uptime and joules per hash.",market:"Liquidity is deeper, but Mt. Gox demonstrates that a large balance on a famous venue can still disappear. The asset survives even when its intermediaries fail.",custody:"Self-custody is no longer a philosophical preference; it is a defence against demonstrated counterparty failure. Running a node separates verification from trust.",facilities:"Three-phase power, airflow and repair logistics now matter as much as raw machine count. A mining site is becoming an engineered system.",energy:"Industrial miners search globally for stranded and low-cost power. Cheap energy offers advantage only when policy, grid access and connectivity remain dependable.",finance:"Mining expansion demands serious fiat, yet borrowing against a volatile and poorly understood business can turn growth into forced failure.",learn:"The ecosystem is converting crisis into doctrine: verify independently, secure keys, distrust concentrated custody and understand the incentives beneath the software.",tech:"Operational maturity now spans firmware, monitoring, storage and security. The winners are building repeatable systems rather than assembling faster machines alone."}},
  {until:"2021-01-01",label:"A global monetary network",copy:{dashboard:"Bitcoin has survived civil war, bubbles and repeated obituaries. It is becoming global settlement infrastructure, while mining consolidates into professional fleets and large pools.",mine:"The S9 era proves that well-run hardware can remain useful across cycles. Scale helps, but efficiency, maintenance and access to power decide who compounds.",market:"Bitcoin now trades around the clock across a global market. Liquidity improves access while leverage and custodial concentration create new systemic risks.",custody:"Hardware wallets, mature nodes and multisignature practices make sovereignty more usable. The remaining question is whether convenience will tempt users back into trusted claims.",facilities:"Warehouses and international mining regions connect Bitcoin to grids, logistics and political jurisdictions. Location becomes a portfolio of risks rather than a cheap tariff.",energy:"Mining is now an energy business with a monetary output. Flexible demand and stranded power create opportunities, while inefficient fleets are exposed at every downturn.",finance:"Professional operators can raise capital, but debt service does not care about hashprice. Liquidity reserves determine whether volatility becomes opportunity or insolvency.",learn:"A deeper body of technical, monetary and historical work is forming. Understanding Bitcoin now means connecting consensus, custody, incentives and monetary history.",tech:"The frontier shifts from simply owning ASICs to running them better: monitoring, firmware, power engineering and resilient treasury operations."}},
  {until:"2024-01-01",label:"Sovereign stress and institutional adoption",copy:{dashboard:"Companies and states now treat Bitcoin as a treasury, policy and energy question. It acts as both a risk asset and an escape route when banks, currencies or borders become restrictive.",mine:"Nation-scale hashrate and supply shocks make mining a geopolitical industry. Operators must survive crackdowns, energy crises and a subsidy that keeps shrinking.",market:"Institutional balance sheets enter the market just as leverage failures expose familiar counterparty risks. Bitcoin's price can collapse while its settlement rules continue unchanged.",custody:"The case for controlling keys sharpens during freezes, failures and political stress. Bitcoin can provide an exit from financial intermediaries only when the holder can actually move it.",facilities:"Mining migrates across continents in response to bans, grid constraints and new power markets. Mobility and jurisdictional resilience become core infrastructure.",energy:"Energy shocks can erase apparently safe margins overnight. Fixed supply meets variable power markets, forcing operators to treat contracts and curtailment as strategic tools.",finance:"Cheap capital can build enormous fleets, but leverage magnifies every fall in hashprice. Fiat collateral and cash runway are now as important as installed machines.",learn:"The debate expands from code into macroeconomics, human rights, energy systems and state power. Competing interpretations reveal what different users need Bitcoin to be.",tech:"Resilience becomes the objective: relocation, hardened nodes, responsive load and robust custody must work together when external systems fail."}},
  {until:null,label:"Institutional asset, permissionless escape valve",copy:{dashboard:"Bitcoin now sits inside ETFs, corporate treasuries and national debates, yet the base network remains open to anyone with keys and a connection. Its institutional scale and permissionless exit function coexist in tension.",mine:"Mining is a global energy and infrastructure industry defending an increasingly valuable settlement network. Margins are thin, capital is sophisticated and operational mistakes are unforgiving.",market:"Brokerage products make price exposure ordinary, but an ETF share is not spendable bitcoin. The market now offers many wrappers around an asset whose distinctive property is settlement without permission.",custody:"Institutions broaden access while self-custody preserves the escape valve. The difference between owning exposure and possessing transferable bearer money has never been clearer.",facilities:"Utility-scale campuses compete for power, grid services and political legitimacy. Mining can monetise flexible demand, but every megawatt deepens regulatory and capital exposure.",energy:"At scale, the operation lives or dies by energy engineering. Grid participation, curtailment, heat, density and long-term contracts shape the economics more than headline machine speed.",finance:"Bitcoin-linked securities and fiat credit broaden the capital stack, but they also reintroduce issuers, covenants and settlement risk. Liquidity remains the defence against forced dependence.",learn:"The curriculum now spans protocol engineering, monetary theory, market structure and geopolitics. The task is to distinguish Bitcoin's verified properties from the stories institutions build around it.",tech:"Mature operations construct block templates, run hardened relays and integrate power, treasury and custody systems. Sophistication should strengthen independent verification rather than replace it."}}
];
function narrativeEra(t=state.time){return NARRATIVE_ERAS.find(era=>!era.until||t<at(era.until))||NARRATIVE_ERAS[NARRATIVE_ERAS.length-1]}
function narrativeCopy(kind,t=state.time){const era=narrativeEra(t);return era.copy[kind]||era.copy.dashboard}
function energyShock(t){return t>=at("2022-02-24")&&t<at("2023-07-01")?1.65:t>=at("2020-03-12")&&t<at("2021-01-01")?.88:1}
function faucetActive(t){return t>=FAUCET_START&&t<FAUCET_END}
function faucetAmount(t){const f=Math.min(1,Math.max(0,(t-FAUCET_START)/(FAUCET_END-FAUCET_START)));return Math.max(.05,5-f*4.9)}
