"use strict";

const originalEnhanceMethod=enhanceMethod;enhanceMethod=function(){originalEnhanceMethod();const guide=document.querySelector(".method");if(!guide)return;guide.innerHTML=guide.innerHTML.replace("Only self-held hot and cold BTC count toward the final score. Lightning must be withdrawn first.","Self-held BTC improves the custody and balance-sheet components of Operator Score, but active era performance supplies 800 of the 1,000 available points.").replace("Liquidity / final score","Liquidity / Operator Score").replace("Spendable; not BTC score","Spendable; supports reserves").replace("Sell first to pay a bill; excluded from score","Sell first to pay a bill").replace("Included in final score","Improves custody and balance quality").replace("Venue-dependent; excluded from score","Venue-dependent; weakens custody ratio").replace("Withdraw before spending or final score","Illiquid until withdrawn")};
const alpha24EnhanceMethod=enhanceMethod;enhanceMethod=function(){alpha24EnhanceMethod();const guide=document.querySelector(".method");if(!guide)return;guide.innerHTML=guide.innerHTML.replace("Connectivity incidents are region-weighted and pause mining/node operation while overhead continues.","Connectivity incidents combine jurisdiction risk with the selected fixed, dual-SIM or fibre plan. Internet charges continue during an outage.").replace("Rent, staff, insurance and node power are separate overhead.","Rent, internet, staff, insurance, node services and finance interest are itemized separately in the obligations timeline.").replace("Monitoring adds 15% to those routing fees.","Monitoring adds 8% to those routing fees.").replace("Tech trees impose prerequisites.","Tech trees impose dependency, historical-date and facility-scale prerequisites, with costs rising by tier.")};
const alpha25EnhanceMethod=enhanceMethod;enhanceMethod=function(){alpha25EnhanceMethod();const guide=document.querySelector(".method");if(!guide)return;guide.innerHTML=guide.innerHTML.replace("Historical dates, major events, broad price and network-hash anchors are recorded inputs.","Historical dates, major events, daily prices and denser network metrics are recorded inputs.").replace("Expected blocks/day are <code>144 × share × uptime</code>, paid at the current subsidy plus modelled fees.","Expected blocks/day use <code>active hash × 86,400 ÷ (difficulty × 2³²)</code>, capped by the effective-competition model, then adjusted for uptime. Rewards use the recorded seven-day mean fee environment plus the protocol subsidy.");guide.insertAdjacentHTML("beforeend",`<section class="strategy-method-guide"><h3>Recorded metric snapshot</h3><p>The historical engine is bundled locally and never changes during a run. It contains daily market prices, recorded difficulty states, a 14-day hashrate mean, seven-day fee and transaction means, and cumulative block-height checkpoints through ${DATA_META.through||"the historical cutoff"}.</p><table><tr><th>Metric</th><th>Offline points</th><th>How the game uses it</th></tr><tr><td>BTC / USD</td><td>${fmtNum(PRICE.length)}</td><td>Daily market value and fiat revenue</td></tr><tr><td>Difficulty</td><td>${fmtNum(DIFFICULTY.length)}</td><td>Primary expected block-yield calculation</td></tr><tr><td>Network hashrate</td><td>${fmtNum(HASH.length)}</td><td>Smoothed context, charts and competitive floor</td></tr><tr><td>Fees / block</td><td>${fmtNum(FEES.length)}</td><td>Seven-day mean added to the subsidy</td></tr><tr><td>Transactions / day</td><td>${fmtNum(TX.length)}</td><td>Seven-day activity context and Lightning scaling</td></tr></table><p class="modal-note">Source: <a href="${DATA_META.sourceUrl||"https://community-api.coinmetrics.io/v4/timeseries/asset-metrics"}" target="_blank" rel="noopener">${DATA_META.source||"Coin Metrics Community Network Data"}</a>. Difficulty is reconstructed from recorded hashrate and block count using the source's published formula. Early competition scaling, hardware economics and operational outcomes remain explicitly modelled for gameplay.</p></section>`)};
const originalApplyEvent=applyEvent;applyEvent=function(e){originalApplyEvent(e);if(e.imp===3&&state.storyPause)state.eventResume=true};
const originalTick=tick;tick=function(silent=false){const old=state.speed;originalTick(silent);if(!silent&&old!==state.speed)setTimer()};
document.addEventListener("visibilitychange",()=>{if(document.visibilityState!=="visible"||!state.started||state.speed<=0||state.ended)return;const stepMs=2000/state.speed,steps=Math.min(3650,Math.floor((Date.now()-(state.lastReal||Date.now()))/stepMs));for(let i=0;i<steps&&state.speed>0&&!state.ended;i++)tick(true);state.lastReal=Date.now();save();render();setTimer()});
if(state.ended)state.speed=0;setTimer();startMempoolTimer();render();
